name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: [3.9, 3.10]  # Add more versions as needed

    runs-on: ubuntu-latest

    steps:

    - name: Python
      run: |
        pip install pyenv
        pyenv install --skip-existing 3.1.5
        pyenv install 3.1.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pytest

    - name: Build Package
      run: |
         python -m build --wheel

    - name: Run Tests
      run: |
        python python_package_exercise_17/tests.py
