name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        python-version:  [3.10]
    runs-on: ubuntu-latest

    steps:
    - name: Install pyenv
      run: |
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
        exec $SHELL

    - name: Python
      run: |
        pyenv install 3.10
        pyenv global 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pytest

    - name: Build Package
      run: |
         python -m build --wheel

    - name: Run Tests
      run: |
        python python_package_exercise_17/tests.py
